apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "digital-trend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "digital-trend.name" . }}
    helm.sh/chart: {{ include "digital-trend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "digital-trend.name" . }}
    version: {{ .Release.Name }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: db
spec:
  replicas: {{ .Values.postgresDb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "digital-trend.name" . }}
      helm.sh/chart: {{ include "digital-trend.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "digital-trend.name" . }}
      version: {{ .Release.Name }}
      release: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "digital-trend.name" . }}
        helm.sh/chart: {{ include "digital-trend.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "digital-trend.name" . }}
        version: {{ .Release.Name }}
        release: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        component: db
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.postgresDb.name }}
          image: "{{ .Values.postgresDb.image.repository }}:{{ default .Values.postgresDb.tag .Values.postgresDb.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "db"
              containerPort: {{ .Values.postgresDb.ports.dbPort }}
            - name: "postgrest"
              containerPort: {{ .Values.postgresDb.ports.postgrestPort }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - -e
                {{ include "digital-trend.probeCommand" . | nindent 16 }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - -e
                {{ include "digital-trend.probeCommand" . | nindent 16 }}
            initialDelaySeconds: 30
            # Allow sufficient amount of time (180 seconds = periodSeconds * failureThreshold)
            # for the registered shutdown handlers to run to completion.
            periodSeconds: 30
            failureThreshold: 10
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.postgresDb.mount }}
              name: volume
              subPath: {{ .Values.postgresDb.subPath }}
{{- include "digital-trend.imagePullSecrets" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: volume
      {{- with .Values.volumeClaim.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.volumeClaim.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volumeClaim.size | quote }}
        storageClassName: {{ .Values.volumeClaim.storageClass }}