{{- if .Values.meetup.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.meetup.name }}
  labels:
    app.kubernetes.io/name: {{ include "digital-trend.name" . }}
    helm.sh/chart: {{ include "digital-trend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: meetup
spec:
  schedule: {{ .Values.meetup.schedule | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "digital-trend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: meetup
  metadata:
    labels:
      app: {{ include "digital-trend.name" . }}
      release: {{ .Release.Name }}
      version: {{ .Release.Name }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: {{ include "digital-trend.name" . }}
            release: {{ .Release.Name }}
            version: {{ .Release.Name }}
            component: meetup
        spec:
          containers:
          - name: {{ .Chart.Name }}-{{ .Values.meetup.name }}
            image: "{{ .Values.meetup.image.repository }}:{{ default .Values.image.tag .Values.meetup.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: PGHOST
                value: {{ .Values.pgHost | quote }}
              - name: PGPORT
                value: !!string {{ .Values.pgPort }}
              - name: PGDATABASE
                value: {{ .Values.pgDatabase | quote }}
              - name: PGUSER
                value: {{ .Values.pgUser | quote }}
              - name: PGPASS
                value: {{ .Values.pgPass | quote }}
              - name: PGSCHEMA
                value: {{ .Values.pgSchema | quote }}
              - name: MEETUP_CLIENT_ID
                value: {{ .Values.meetup.meetupClientId | quote }}
              - name: MEETUP_CLIENT_SECRET
                value: {{ .Values.meetup.meetupClientSecret | quote }}
              - name: MEETUP_CODE
                value: {{ .Values.meetup.meetupCode | quote }}
              {{- if .Values.meetup.meetupTopics }}
              - name: MEETUP_TOPICS
                value: {{ .Values.meetup.meetupTopics | quote }}
              {{- end }}
              {{- if .Values.meetup.meetupCities }}
              - name: MEETUP_CITIES
                value: {{ .Values.meetup.meetupCities | quote }}
              {{- end }}
              {{- if .Values.meetup.meetupKeywords }}
              - name: MEETUP_KEYWORDS
                value: {{ .Values.meetup.meetupKeywords | quote }}
              {{- end }}
              {{- if .Values.meetup.meetupRedirectUrl }}
              - name: MEETUP_REDIRECT_URL
                value: {{ .Values.meetup.meetupRedirectUrl | quote }}
              {{- end }}
              {{- if .Values.meetup.meetupRateLimit }}
              - name: MEETUP_RATE_LIMIT
                value: !!string {{ .Values.meetup.meetupRateLimit }}
              {{- end }}
            ports:
            - name: "db"
              containerPort: 80
          restartPolicy: OnFailure
{{- include "digital-trend.imagePullSecrets" . | indent 10 }}
{{- end }}